version: '3'
services:
  mongo:
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  hivemq:
    image: hivemq/hivemq4
    ports:
      - "8081:8080"
      - "1883:1883"
